import { chromium } from "playwright-core";
const exe = `${process.env.HOME}/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome`;
const browser = await chromium.launch({ executablePath: exe });
const page = await browser.newPage();
page.on("pageerror", (e) => console.log("pageerror:", e.message));
await page.goto("https://nutristatic.org/?q=" + encodeURIComponent("solar s_stem"));
await page.waitForFunction(() => document.querySelectorAll("#results span").length > 0, null, { timeout: 90000 });
console.log("first result:", await page.$eval("#results span", (e) => e.textContent));
console.log("index:", await page.textContent("#indexinfo"));
await page.screenshot({ path: "prod.png" });
await browser.close();
console.log("PROD OK");
