import { chromium } from "playwright-core";
const exe = `${process.env.HOME}/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome`;
const browser = await chromium.launch({ executablePath: exe });
const page = await (await browser.newContext()).newPage({ viewport: { width: 900, height: 1100 } });
await page.goto("https://nutristatic.org/usage.html");
await page.screenshot({ path: "/tmp/claude-1000/-home-ps-nutri/0c9d7ad3-bdda-4fce-9430-0c7cf8ef8467/scratchpad/usage.png" });
await page.goto("https://nutristatic.org/");
await page.waitForSelector("#examples li");
await page.screenshot({ path: "/tmp/claude-1000/-home-ps-nutri/0c9d7ad3-bdda-4fce-9430-0c7cf8ef8467/scratchpad/home-new.png" });
await browser.close();
console.log("SHOTS OK");
